name: Smoke Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  smoke-tests:
      if: github.event_name != 'workflow_dispatch'
      runs-on: ubuntu-latest

      steps:
        - name: Check Allure results
          if: always()
          run: |
            ls -la build
            ls -la build/allure-results

        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Java 17
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 17

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Run Smoke tests
          run: ./gradlew clean smokeTest
          continue-on-error: true

        - name: Upload Allure results
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: allure-results
            path: build/allure-results

        - name: Generate Allure Report
          run: ./gradlew build/allureReport

        - name: Upload Allure Report
          uses: actions/upload-artifact@v4
          with:
            name: allure-report
            path: build/reports/allure-report/allureReport